import { query } from './pool.js';
import {
  mapSchool,
  mapDepartment,
  mapTeacher,
  mapStudent,
  mapSchoolClass,
  mapLessonPlan,
  mapAssessment,
  mapAttendance,
  mapTeacherTraining,
  mapSchoolCheckIn,
  mapExam,
  mapTrainingMaterial,
  mapTeachingNote,
  mapStudentGradeEntry,
  mapTeacherResource,
  mapTeacherFeedback,
  mapParentMessage,
  mapTeacherCheckInPrompt,
  mapNotification,
} from '../lib/serialize.js';

export async function loadBootstrap() {
  const [
    schools,
    departments,
    teachers,
    students,
    classes,
    lessonPlans,
    assessments,
    attendance,
    trainings,
    checkIns,
    exams,
    trainingMaterials,
    teachingNotes,
    studentGradeEntries,
    teacherResources,
    teacherFeedbacks,
    parentMessages,
    teacherCheckInPrompts,
    notifications,
  ] = await Promise.all([
    query('SELECT * FROM schools ORDER BY name'),
    query('SELECT * FROM departments ORDER BY name'),
    query('SELECT * FROM teachers ORDER BY name'),
    query('SELECT * FROM students ORDER BY name'),
    query('SELECT * FROM school_classes ORDER BY grade, section'),
    query('SELECT * FROM lesson_plans ORDER BY created_at DESC'),
    query('SELECT * FROM assessments ORDER BY created_at DESC'),
    query('SELECT * FROM attendance ORDER BY date DESC'),
    query('SELECT * FROM teacher_trainings ORDER BY start_date'),
    query('SELECT * FROM school_check_ins ORDER BY date DESC'),
    query('SELECT * FROM exams ORDER BY created_at DESC'),
    query('SELECT * FROM training_materials ORDER BY uploaded_at DESC'),
    query('SELECT * FROM teaching_notes ORDER BY created_at DESC'),
    query('SELECT * FROM student_grade_entries ORDER BY recorded_at DESC'),
    query('SELECT * FROM teacher_resources ORDER BY created_at DESC'),
    query('SELECT * FROM teacher_feedbacks ORDER BY date DESC'),
    query('SELECT * FROM parent_messages ORDER BY sent_at DESC'),
    query('SELECT * FROM teacher_check_in_prompts ORDER BY due_date'),
    query('SELECT * FROM notifications ORDER BY created_at DESC'),
  ]);

  return {
    schools: schools.rows.map(mapSchool),
    departments: departments.rows.map(mapDepartment),
    teachers: teachers.rows.map(mapTeacher),
    students: students.rows.map(mapStudent),
    classes: classes.rows.map(mapSchoolClass),
    lessonPlans: lessonPlans.rows.map(mapLessonPlan),
    assessments: assessments.rows.map(mapAssessment),
    attendance: attendance.rows.map(mapAttendance),
    trainings: trainings.rows.map(mapTeacherTraining),
    checkIns: checkIns.rows.map(mapSchoolCheckIn),
    exams: exams.rows.map(mapExam),
    trainingMaterials: trainingMaterials.rows.map(mapTrainingMaterial),
    teachingNotes: teachingNotes.rows.map(mapTeachingNote),
    studentGradeEntries: studentGradeEntries.rows.map(mapStudentGradeEntry),
    teacherResources: teacherResources.rows.map(mapTeacherResource),
    teacherFeedbacks: teacherFeedbacks.rows.map(mapTeacherFeedback),
    parentMessages: parentMessages.rows.map(mapParentMessage),
    teacherCheckInPrompts: teacherCheckInPrompts.rows.map(mapTeacherCheckInPrompt),
    notifications: notifications.rows.map(mapNotification),
  };
}
